server {
    listen 80;

    location = / {
        return 302 /ui/;
    }

    location / {
        proxy_pass http://vault:8200;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
